### ISSUE TITLE
使用paddle，拖拉框不能太小，不然识别率超低

### ISSUE THREAD

**Issue by derQiQ** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#10]

**Comment by derQiQ** [comment]
以下面为例，识别10次带“About”部分基本正确10次，而不带“About”的部分只大至50%识别正确率
----------------------------------------------
About

天若ocr开源版本的本地版，采用
Chinese-lite和paddleocr识别框架
----------------------------------------------
天若ocr开源版本的本地版，采用
Chinese-lite和paddleocr识别框架
----------------------------------------------

**Comment by wangfreexx** [comment]
已经在gitee回答
