### ISSUE TITLE
关于翻译接口错误的问题

### ISSUE THREAD

**Issue by Zou-Yi** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#12]
目前有两个问题想请教一下
1、谷歌翻译的接口是否有上限之类的，用了一段时间后（大概翻译了几十次和一千多字符左右）就直接报错了
[谷歌接口报错]：
1.网络错误或者文本过长。
2.谷歌接口可能对于某些网络不能用，具体不清楚。可以尝试挂VPN试试。
3.这个问题我没办法修复

2、输入百度翻译的api后无法使用百度翻译，正常谷歌翻译可用的情况下也是，排除了网络和api问题，想问问是不是没有用百度的通用翻译API HTTPS 地址：https://fanyi-api.baidu.com/api/trans/vip/translate
![image](https://user-images.githubusercontent.com/25612398/184612515-b03cbb40-8cba-4d39-825a-21122b33eda8.png)
报错：翻译超时，请检查网络，或更换翻译平台。

**Comment by wangfreexx** [comment]
1.谷歌是否能用全凭运气
2.近期我查下，有问题会及时修复

**Comment by wangfreexx** [comment]
以及测试过，百度翻译没有问题，翻译接口为http://api.fanyi.baidu.com/api/trans/vip/translate，请检查是不是api填写错误地方了

**Comment by Zou-Yi** [comment]
> 以及测试过，百度翻译没有问题，翻译接口为[http://api.fanyi.baidu.com/api/trans/vip/translate，请检查是不是api填写错误地方了](http://api.fanyi.baidu.com/api/trans/vip/translate%EF%BC%8C%E8%AF%B7%E6%A3%80%E6%9F%A5%E6%98%AF%E4%B8%8D%E6%98%AFapi%E5%A1%AB%E5%86%99%E9%94%99%E8%AF%AF%E5%9C%B0%E6%96%B9%E4%BA%86)

sorry 是我开通错服务了 怪不得一直都翻译不了
