### ISSUE TITLE
一点小建议，作者大大可以看下

### ISSUE THREAD

**Issue by kfcx** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#14]
作者你好，众所周知OCR接口容易失效是一大痛点，所以增加自定义OCR接口很重要，相信很多人也有这样的需求。

功能需求：
由用户自定义OCR接口，程序读取用户填写的配置信息：

OCR API URL ：http://example.com
Data: {
   .....
}

程序将截图转base64添加到Data，然后Post请求OCR URL，再由自定义OCR接口返回识别参数（返回的参数格式由你决定，用户根据你的参数格式做接口修改）

请作者大大可以采纳我的建议，我代表大家感谢你的付出！

**Comment by wangfreexx** [comment]
想法确实好，但是又两个原因目前（可能以后也不会）不会做
1.没时间，要毕业
2.本地接口何来失效，不会失效，永远不会，这个本地就是为了解决OCR接口容易失效的痛点，等10年后也不会失效
