### ISSUE TITLE
静默识别不太好吧。

### ISSUE THREAD

**Issue by xelc** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#17]
本想反映置顶无效，结果发现是静默识别默认开启的问题，很多时候也不能保证识别百分百正确，还是需要在显示界面编辑一下，还有识别英文看翻译。

**Comment by wangfreexx** [comment]
其实属于编程时复制的上一个选项导致默认为true，也就是选中状态，但是难得为了这一个新开一个版本了，等下个版本，确实静默识别默认开启不爽，哈哈哈哈
