### ISSUE TITLE
不能设置代理么？

### ISSUE THREAD

**Issue by ghost** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#18]
印象中原来有设置代理的功能啊，是移除了么

不能设置代理，Google 翻译不能用了，得申请国内的接口
![image](https://user-images.githubusercontent.com/95120835/208289104-9ee740b3-6d94-4dbc-9e5b-5e735e0e01ed.png)

作者考虑做一下这个功能么？

**Comment by wangfreexx** [comment]
没有考虑代理功能，原来也没有，请尝试host等方式修复谷歌，或者申请国内api
