### ISSUE TITLE
关于谷歌翻译的建议

### ISSUE THREAD

**Issue by dawnli139** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#19]
建议谷歌翻译直接更改为代理的接口

**Comment by dawnli139** [comment]
https://www.52pojie.cn/thread-1730450-1-1.html
这个是我看到的，感觉可以把代理的这个部分接上来

**Comment by wangfreexx** [comment]
需要权限我看不到

**Comment by dawnli139** [comment]
> 

我的疏忽，应该是同一作者的知乎页面：
https://zhuanlan.zhihu.com/p/594474596
里面有放源码，具体改动应该是添加了一个谷歌翻译的接口函数，我直接加上去是可以work的

**Comment by wangfreexx** [comment]
我看了下，也不算是直接的代理的接口，还是自己的接口。感觉不如host或者dns或者全局代理方便。天若本来是有代理设置的，原作者好像关闭了，有空我看看给他弄回来，但是个人感觉没有必要，我一直用的host大法

**Comment by dawnli139** [comment]
对，如果能恢复代理设置是最好，现在host我这里ping半天没有一个能用的，大佬有空再更新下叭~

**Comment by wangfreexx** [comment]
已添加
