### ISSUE TITLE
文本识别后，有多行的文本，自动复制的不能换行

### ISSUE THREAD

**Issue by aaffjj** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#25]
文本识别后，有多行的文本，自动复制的不能换行

需要手动全选复制才能换行，

修改版的自动识别后直接把多行连城一行了

**Comment by wangfreexx** [comment]
因为自动复制会对文本进行合并处理

**Comment by aaffjj** [comment]
> 因为自动复制会对文本进行合并处理

现在试用的新版的可以不合并这样的复制，不知道这个老版本的不知道能不能也这样修改一下，比较方便

**Comment by wangfreexx** [comment]
新版本已经修正了，你试试

**Comment by aaffjj** [comment]
> 新版已经修改好了，你试试

刚下载了，可以了，完美解决问题了
