### ISSUE TITLE
設置窗口顯示不完

### ISSUE THREAD

**Issue by kxwuli** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#26]
設置的窗口不靈活，導致一些設定功能不顯示。比如：Tab1‘常規’的自動保存被蓋了一半。

**Comment by wangfreexx** [comment]
![image](https://user-images.githubusercontent.com/23137882/230262550-ccdbfd43-e564-4685-aa26-8dde0de44f02.png)
我这里没有看到这个问题
