### ISSUE TITLE
拆分，朗读等功能别删呀，求修复一下。

### ISSUE THREAD

**Issue by kinaka** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#28]
拆分、合并、分段都是不错的功能，朗读也可以来朗读英文。

**Comment by wangfreexx** [comment]
这些功能不错是不错，可是从我接手这个开始他们就不能用，因为api替换或者网站失效等原因，我从v1版本就已经删除了，只是这个版本吧图标删除了，你用原来版本会发现这些功能根本没用的

**Comment by kinaka** [comment]
> 这些功能不错是不错，可是从我接手这个开始他们就不能用，因为api替换或者网站失效等原因，我从v1版本就已经删除了，只是这个版本吧图标删除了，你用原来版本会发现这些功能根本没用的

天若OCR原版4.49上是依然可以使用的拆分、朗读是可用的，希望测试一下。

**Comment by wangfreexx** [comment]
如果可用，那建议使用原版，我一开始就删除了相关代码，现在再找已经记不得位置了
