### ISSUE TITLE
更新到 1.3.9 版后，启动时初始化失败。上一版v1.3.8.2运行正常。

### ISSUE THREAD

**Issue by shuaiyewl** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#30]
更新到 1.3.9 版后，启动时初始化失败。上一版v1.3.8.2运行正常。
所以不要说什么运行库的问题。应该就是新版的bug。

![2023-05-30_214852](https://github.com/wangfreexx/wangfreexx-tianruoocr-cl-paddle/assets/102898902/7900d9e8-acaa-4c28-9a70-62ee79752357)

**Comment by wangfreexx** [comment]
哦哦哦
把1.3.8.2的onnxruntime.dll替换下1.3.9的，忘记替换了

**Comment by shuaiyewl** [comment]
谢谢，已OK。
