### ISSUE TITLE
大佬, 能问下天若ocr的接口问题吗, 官方这个接口啥意思呀

### ISSUE THREAD

**Issue by li54426** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#32]
大佬, 能问下天若ocr的接口问题吗, 官方这个接口啥意思呀	//image：要识别的图片
	public static string OCR_Custom(Image image)
	{
	    //string url = "";
	    //string poststr ="";
	    //string result =CustomHelp.HttpPost(url,poststr);
	    //获取请求获取解析结果后按照下面格式进行解析
	    TxtFormat.Root jsonRoot=new TxtFormat.Root();
	    jsonRoot.result=new List<TxtFormat.TextBlock>();
	    jsonRoot.isHasLocation=true;//判断是否含有坐标返回
	    for(int i=0; i<5; i++)//遍历返回的json字符串
	    {
	        TxtFormat.TextBlock textBlock = new TxtFormat.TextBlock();
	        textBlock.Text = "公式测试文本"+i.ToString();//json内的文本
	        textBlock.TopLeft = new Point(0,0);//左上角坐标
	        textBlock.TopRight = new Point(0,0);//右上角坐标
	        textBlock.BottomRight =new Point(0,0);//右下角坐标
	        textBlock.BottomLeft =new Point(0,0);//左下角坐标
	        jsonRoot.result.Add(textBlock);
	    }
	    string json = JsonConvert.SerializeObject(jsonRoot);
	    return json;
	}

**Comment by wangfreexx** [comment]
接口就是传入图片返回结果。这是哪里找的，我不是原作者，有些不清楚
