### ISSUE TITLE
打包的文件名问题

### ISSUE THREAD

**Issue by 007ayong** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#34]
希望作者每次更新文件名能保持命名规律，方便添加到 scoop 中自动更新

**Comment by wangfreexx** [comment]
麻烦说一下命名规律如何合适，我之前都是随心所欲的

**Comment by 007ayong** [comment]
> 

看之前都是 tianruoocr-cl-v1.x.x.x.7z 这样，然后文件名里和 tag 的版本号是一致的，最新一版 tianruoocr-cl-v1.3.9**v2**.7z 突然多出来一个 v2

**Comment by wangfreexx** [comment]
哦哦，v2属于意外，有个非常小的错误，下次我注意
