### ISSUE TITLE
如何设置默认字体

### ISSUE THREAD

**Issue by Kxysj** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#35]
作者您好，
微软雅黑这个字号很小而且很粗，字很挤看着太累了，不如宋体看着顺眼，现在是只能识别后再修改成宋体，而且下次识别的结果还是微软雅黑的，很麻烦。请问怎么能把默认字体设置成宋体。

期待回复。谢谢

**Comment by wangfreexx** [comment]
默认字体需要重新编译打包，之前是别人说宋体不好看改过来的....我给你编译了一个宋体版本，你替换下exe就可以，[https://wwnu.lanzouk.com/i50Vf12zukod](https://wwnu.lanzouk.com/i50Vf12zukod)
