### ISSUE TITLE
一切都很好,只有一个英文识别问题!

### ISSUE THREAD

**Issue by superpink617** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#42]
无论是CL还是Pa接口,英文识别都有毛病;首先CL无法识别全部英文,其次Pa接口选择英文数字模式后,可以识别出全部英文,但是无法自动识别英文单词之间的空格,导致长达几行的英文段落中的所有单词都连在了一起→既没法阅读也没法翻译

**Comment by wangfreexx** [comment]
你好，由于精力有限等很多原因不再维护，推荐使用umi-ocr，我也在使用
