### ISSUE TITLE
English interface

### ISSUE THREAD

**Issue by vanbang9710** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#44]
I don't know Chinese so I don't how to change to English interface

**Comment by wangfreexx** [comment]
Hello, thank you for your attention, due to limited energy and many other reasons no longer maintenance, recommend using umi-ocr[umi-ocr](https://github.com/hiroi-sora/Umi-OCR), more convenient than this, and have English, I am also using（This passage was translated into English by software）
