### ISSUE TITLE
能不能适配MAC呀，这个项目太棒啦

### ISSUE THREAD

**Issue by AlanDinkle** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#5]
如果可以就太棒啦(●。∀。●)精力不够就不必啦~

**Comment by wangfreexx** [comment]
抱歉，这个是使用c#编程，我没有学习跨平台的支持

**Comment by jiaoting** [comment]
> 如果可以就太棒啦(●。∀。●)精力不够就不必啦~

mac上的ocr，可以使用ishot，里面带免费ocr（可以安装两个软件实现免费vip升级，那两个软件都很好用的）
