### ISSUE TITLE
如何更新模型

### ISSUE THREAD

**Issue by jiaoting** [wangfreexx/wangfreexx-tianruoocr-cl-paddle#8]
![image](https://user-images.githubusercontent.com/12553424/182541896-6945452f-453c-4443-9039-c171759ae4fc.png)
这些文件，如何更新呀？我看paddle-ocr出了v3版本了，想更新一下

**Comment by wangfreexx** [comment]
直接按名字替换就行，比如带xxxx_cls_infer_xxxxv3.onnx改成cls_infer.onnx就行

**Comment by wangfreexx** [comment]
已经更新了
